server:
  port: 9002
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/clientside}
    username: ${SPRING_DATASOURCE_USERNAME:clientuserr}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_2s8LBE_oJIbedpG4lSx}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}